"""
Django settings for library_system project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bfhehav11h!3+_13b3q8igbkfh-egpcludmizsrj++p6f64hlg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Custom User model
AUTH_USER_MODEL = 'Books.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # for allauth account registration
    # local apps
    'api',
    'Books',

    # 3rd party
    'rest_framework',
    # 'rest_framework.authtoken',   # for token authentication
    'rest_framework_simplejwt', # JWT authentication
    'rest_framework_simplejwt.token_blacklist',  # to blacklist the JWT token
    
    # dj-rest-auth
    'dj_rest_auth',      # REST auth endpoints (login, logout, password reset, etc)
    'dj_rest_auth.registration', # 
    
    # all auth registration
    'allauth',
    'allauth.account',      # if email verification needed
    'allauth.socialaccount',    
    
    'drf_spectacular', # for schema/documentation
    'django_filters',   # for filtering in DRF views

    # additional to handle CORS
    'corsheaders',   
]

SITE_ID = 1  # for allauth account registration

# Settings for dj-rest-auth
REST_AUTH = {
    'TOKEN_MODEL': None,  # to disable token model if using JWT
    'USE_JWT': True,
    'JWT_AUTH_REFRESH_COOKIE': 'jwt_refresh_token',  # cookie name for refresh token

    # 'JWT_AUTH_HTTPONLY': True,  # default True, makes the cookie HttpOnly -> not accessible via JavaScript(helps prevent XSS attacks)
}


# REST Framework global settings
# - Default: (authentication: Session + Basic, permission: AllowAny)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Settings for Simple JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    
    # Token rotation and blacklisting settings -> Prevents stolen refresh tokens from being re-used
    "ROTATE_REFRESH_TOKENS": True,         # Generates NEW refresh token each refresh
    "BLACKLIST_AFTER_ROTATION": True,     # Old refresh token becomes invalid    
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',    # to handle CORS(Cross-Origin Resource Sharing) ->must be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    

    'allauth.account.middleware.AccountMiddleware',  # for allauth account registration
]

# Allow React (localhost:5173) to access the Django backend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True    # Allow cookies to be included in cross-site HTTP requests (used for writing cookies in frontend)


ROOT_URLCONF = 'library_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

