# Generated by Django 5.2.8 on 2025-11-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_publisher_remove_book_authors_remove_book_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='feature_image',
            field=models.ImageField(blank=True, default='books/default-book.jpg', upload_to='books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
