# Generated by Django 5.2.8 on 2025-11-17 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_bookreview_options_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('inquiry', 'Inquiry')], default='inquiry', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
